mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(arg='news.urls', namespace='news')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include('debug_toolbar.urls'))]

news/urls.py
from django.urls import path

from .apps import NewsConfig
import news.views as news

app_name = NewsConfig.name

urlpatterns = [
    path('', news.HomeNews.as_view(), name='home'),
    # path('', news.index, name='home'),

    path('category/<int:category_id>/', news.NewsByCategory.as_view(), name='category'),
    path('news/<int:pk>/', news.ViewNews.as_view(), name='view_news'),
    path('news/add-news/', news.CreateNews.as_view(), name='add_news'),

    path('register/', news.register, name='register'),
    path('login/', news.user_login, name='login'),
    path('logout/', news.user_logout, name='logout'),
]

templates/inc/_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'news:home' %}">Новостной сайт xD</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'news:home' %}">Главная</a>
                </li>

{#                {% if user.is_authenticated %}#}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'news:add_news' %}">Добавить
                            новость</a>
                    </li>
{#                {% endif %}#}

                <li class="nav-item">
                        <span class="nav-link">
                            Сейчас на сервере {% now 'Y-m-d H:i' %}
                        </span>
                </li>
            </ul>

            <span class="navbar-text">
                {% if not user.is_authenticated %}
                    <a href="{% url 'news:register' %}">Регистрация</a>
                    <a href="{% url 'news:login' %}">Войти</a>
                {% else %}
                    <span>Добро пожаловать, {{ user.username }} |</span>
                    {% if user.is_staff %}
                        <a href="/admin/" target="_blank">Админка</a>
                    {% endif %}
                    <a href="{% url 'news:logout' %}">Выйти</a>
                {% endif %}
            </span>
        </div>
    </div>
</nav>

templates/inc/_sidebar.html
{% load news_tags %}
{% get_list_categories as categories %}

{% comment %}
<div class="list-group">
    {% for item in categories %}
        <a href="{% url 'news:category' item.pk %}" class="list-group-item list-group-item-action"
           aria-current="true">{{ item.title }}</a>
    {% endfor %}
</div>

<br>
{% endcomment %}

{% show_categories %}